### ISSUE TITLE
Move to Mozilla's DeepSpeech? 

### ISSUE THREAD

**Issue by breznak** [MycroftAI/mimic1#157]
Will you move to https://github.com/mozilla/DeepSpeech 
as mentioned on Mark II Kickstarter page? 
I'm asking for possible language TTS support for other languages than English (ie #140  )

**Comment by forslund** [comment]
Deepspeech is for Speech-to-text, while mimic is a text-to-speech engine. For better language support check out the modularized version of mimic (https://github.com/MycroftAI/mimic-full)

**Comment by breznak** [comment]
Thanks for clarification, @forslund ! As there is a "mimic-french" repo, etc.. is there a list of all languages supported by the Mimic TTS? And what is the procedure to add a new lang support? What I gather Mimic is a "HTS" (HMM-based TTS), so can models & voices from other toolkits be imported (festival, ..)?

**Comment by forslund** [comment]
Well it supports both HTS and Clustergen. @zeehio has created the French and Spanish modules. I'm not very well versed in the nitty-gritty details of it. Maybe he can help?

**Comment by jharbott** [comment]
Actually there is https://github.com/mozilla/tts though it looks pretty alpha. Might still be interesting to watch in the longer run.

**Comment by LuccoJ** [comment]
It doesn't seem to be what Mozilla is developing above, but [Deep Voice](http://research.baidu.com/deep-voice-production-quality-text-speech-system-constructed-entirely-deep-neural-networks/) also exist at Baidu as a "twin" paper to the Deep Speech paper that Mozilla developed their speech recognition system on.
