### ISSUE TITLE
Time for a new release ?

### ISSUE THREAD

**Issue by ffontaine** [MycroftAI/mimic1#181]
Last release is more than two years old. Do you plan to make a new official release any time soon?

**Comment by earboxer** [comment]
Yeah, a release would be nice, since the current release doesn't include the prosody pitch changes.

**Comment by PureTryOut** [comment]
This issue can probably be closed, last release was 1.3.0.1 on the 6th of March.

**Comment by ffontaine** [comment]
Indeed, done
