### ISSUE TITLE
./dependencies.sh --prefix="/usr/local" : FTPunreachable

### ISSUE THREAD

**Issue by HorizonKane** [MycroftAI/mimic1#184]
I am trying to install mimic1 on my raspberry Pi running Debian Stretch Lite.

I have the following problem when running the dependencies script:

pi@raspberrypi:~/mimic1 $ ./dependencies.sh --prefix="/usr/local"
/usr/bin/pkg-config
Have PCRE2? [no]
--2019-09-26 05:25:34--  ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/p                               cre2-10.23.zip
           => ‘pcre2-10.23.zip’
Resolving ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)... 131.111.8.115
Connecting to ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)|131.111.8.115|:21... failed: Connection timed out.
Retrying.

--2019-09-26 05:27:49--  ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.23.zip
  (try: 2) => ‘pcre2-10.23.zip’
Connecting to ftp.csx.cam.ac.uk (ftp.csx.cam.ac.uk)|131.111.8.115|:21... failed: Connection timed out.
Retrying.

**Comment by krisgesling** [comment]
Hi there,

Have a fix in motion, but the simplest solution right now is to replace the download url on line 54 with:
ftp://ftp.pcre.org/pub/pcre/pcre2-10.23.zip

**Comment by HorizonKane** [comment]
I did exactly that to fix and just wanted to post it. You are blazing fast :D

**Comment by forslund** [comment]
The fix has now been merged, closing this one.
