### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by HorizonKane** [MycroftAI/mimic1#185]
Hi,

all steps went fine when installing on my raspi 3 b+, but make check fails:

```
pi@raspberrypi:~/mimic1 $ make check
Making check in .
make[1]: Entering directory '/home/pi/mimic1'
make  unittests/hrg_test unittests/regex_test unittests/string_test unittests/token_test unittests/voice_select unittests/wave_test unittests/lex_test unittests/lts_test unittests/nums_test  testsuite/asciiS2U testsuite/asciiU2S testsuite/bin2ascii testsuite/by_word testsuite/combine_waves testsuite/compare_wave testsuite/kal_test testsuite/lex_lookup testsuite/lpc_resynth testsuite/lpc_test2 testsuite/lpc_test testsuite/multi_thread testsuite/play_client testsuite/play_server testsuite/play_sync testsuite/play_wave testsuite/rfc testsuite/time_voice_load testsuite/utt_test
make[2]: Entering directory '/home/pi/mimic1'
  CC       unittests/hrg_test_main.o
  CCLD     unittests/hrg_test
  CC       unittests/regex_test_main.o
  CCLD     unittests/regex_test
  CC       unittests/string_test_main.o
  CCLD     unittests/string_test
  CC       unittests/unittests_token_test-token_test_main.o
  CCLD     unittests/token_test
  CC       unittests/unittests_voice_select-voice_select_test_main.o
  CCLD     unittests/voice_select
  CC       unittests/unittests_wave_test-wave_test_main.o
  CCLD     unittests/wave_test
  CC       unittests/lex_test_main.o
  CCLD     unittests/lex_test
  CC       unittests/lts_test_main.o
  CCLD     unittests/lts_test
  CC       unittests/unittests_nums_test-nums_test_main.o
  CCLD     unittests/nums_test
  CC       testsuite/asciiS2U_main.o
  CCLD     testsuite/asciiS2U
  CC       testsuite/asciiU2S_main.o
  CCLD     testsuite/asciiU2S
  CC       testsuite/bin2ascii_main.o
  CCLD     testsuite/bin2ascii
  CC       testsuite/by_word_main.o
  CCLD     testsuite/by_word
  CC       testsuite/combine_waves_main.o
  CCLD     testsuite/combine_waves
  CC       testsuite/compare_wave_main.o
  CCLD     testsuite/compare_wave
  CC       testsuite/kal_test_main.o
  CCLD     testsuite/kal_test
  CC       testsuite/lex_lookup_main.o
  CCLD     testsuite/lex_lookup
  CC       testsuite/lpc_resynth_main.o
  CCLD     testsuite/lpc_resynth
  CC       testsuite/lpc_test2_main.o
  CCLD     testsuite/lpc_test2
  CC       testsuite/lpc_test_main.o
  CCLD     testsuite/lpc_test
  CC       testsuite/testsuite_multi_thread-multi_thread_main.o
  CCLD     testsuite/multi_thread
  CC       testsuite/play_client_main.o
  CCLD     testsuite/play_client
  CC       testsuite/play_server_main.o
  CCLD     testsuite/play_server
  CC       testsuite/play_sync_main.o
  CCLD     testsuite/play_sync
  CC       testsuite/play_wave_main.o
  CCLD     testsuite/play_wave
  CC       testsuite/rfc_main.o
  CCLD     testsuite/rfc
  CC       testsuite/time_voice_load.o
  CCLD     testsuite/time_voice_load
  CC       testsuite/utt_test_main.o
  CCLD     testsuite/utt_test
make[2]: Leaving directory '/home/pi/mimic1'
make  check-TESTS
make[2]: Entering directory '/home/pi/mimic1'
make[3]: Entering directory '/home/pi/mimic1'
FAIL: unittests/hrg_test
FAIL: unittests/regex_test
FAIL: unittests/string_test
FAIL: unittests/token_test
FAIL: unittests/voice_select
FAIL: unittests/wave_test
FAIL: unittests/lex_test
FAIL: unittests/lts_test
FAIL: unittests/nums_test
============================================================================
Testsuite summary for mimic 1.1.0.9000
============================================================================
# TOTAL: 9
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  9
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/MycroftAI/mimic/issues
============================================================================
Makefile:4695: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/pi/mimic1'
Makefile:4801: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/pi/mimic1'
Makefile:5095: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/pi/mimic1'
Makefile:4581: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
Any idea whats wrong?

**Comment by HorizonKane** [comment]
pi@raspberrypi:~/mimic1 $ cat test-suite.log
========================================
   mimic 1.1.0.9000: ./test-suite.log
========================================

# TOTAL: 9
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  9
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: unittests/hrg_test
========================

./unittests/hrg_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/hrg_test (exit status: 127)

FAIL: unittests/regex_test
==========================

./unittests/regex_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/regex_test (exit status: 127)

FAIL: unittests/string_test
===========================

./unittests/string_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/string_test (exit status: 127)

FAIL: unittests/token_test
==========================

./unittests/token_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/token_test (exit status: 127)

FAIL: unittests/voice_select
============================

./unittests/voice_select: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/voice_select (exit status: 127)

FAIL: unittests/wave_test
=========================

./unittests/wave_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/wave_test (exit status: 127)

FAIL: unittests/lex_test
========================

./unittests/lex_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/lex_test (exit status: 127)

FAIL: unittests/lts_test
========================

./unittests/lts_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/lts_test (exit status: 127)

From the test-suite.log:

FAIL: unittests/nums_test
=========================

./unittests/nums_test: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory
FAIL unittests/nums_test (exit status: 127)

**Comment by HorizonKane** [comment]
Already found the solution here:

https://github.com/MycroftAI/mimic1/issues/131

**Comment by krisgesling** [comment]
Excellent, glad it's working :)
