### ISSUE TITLE
SSML: add support for modifying the pitch for audio response

### ISSUE THREAD

**Issue by INsiteLabDev** [MycroftAI/mimic1#189]
My team and I are trying to modify volume, speed, and pitch of the audio response with ssml tags but we have only succeeded in modifying speed and volume.

* I'm running mycroft-core
* With British male as the voice

Steps to replicate issue:
1. Change this line of code https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/audio/speech.py#L87 to 

mute_and_speak("<speak>Prosody can be used to change the way words sound. The following words are <prosody volume='75%'> quite a bit softer than the rest of this passage. </prosody> Each morning when I wake up, <prosody rate='0.5'>I speak quite slowly and deliberately until I have my coffee.</prosody> I can also change the pitch of my voice using prosody. Do you like <prosody pitch='+10'> speech with a pitch that is higher, </prosody> or <prosody pitch='-10'> is a lower pitch preferable? </prosody></speak>", ident, listen)

2. run mycroft-core and ask Mycroft a question. As of now, Mycroft will not change the pitch.

We would like for someone to add support for modifying pitch for the audio response. In addition, we would like to know what tags and range of values for each tag would appropriately modify the pitch.

**Comment by forslund** [comment]
Hi,

as you noted mimic doesn't support the changing the pitch yet as commented [here](https://github.com/MycroftAI/mimic1/blob/development/src/synth/cst_ssml.c#L50). I'll look into adding it but my guess is that it's going to require quite some work...

**Comment by earboxer** [comment]
Mimic does support changing the pitch (as of https://github.com/MycroftAI/mimic1/pull/168).

I guess I didn't update that comment in the header.

`prosody@pitch` and `prosody@range` attributes are supported. The units are hertz. (even if you don't specify units... the SSML parsing doesn't handle alternate units).

```
Do you like speech with a pitch that is <prosody pitch=440>higher, or is a <prosody pitch=220>lower pitch preferable?
```

the range attribute is kind of like messing with autotune. With a range of 0, the pitch will be very precise (and sound a little robotic). I think a range of about 20 still sounded natural, but kept on pitch enough for it to sound like it was singing. (in your example, you probably don't want to change the range).

**Comment by forslund** [comment]
Thanks @earboxer Totally forgot about that PR.

**Comment by earboxer** [comment]
@forslund can we maybe tag a new release? 1.2.0.2 was tagged in 2017

**Comment by forslund** [comment]
Yeah, I'll handle it.

**Comment by forslund** [comment]
As pitch exists thanks to @earboxer I'm closing this issue.
